version: '3'
services:
  app:
    volumes:
      - ./:/chart-tool
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
      - '3030:3030'
    depends_on:
      - mongo
      - browserless
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/meteor
      MAIL_URL: smtp://user:password@mailhost:port/
      DOCKER: 'TRUE'
      PORT: 3000
      ROOT_URL: http://app
      CHROME_REMOTE_URL: ws://browserless:3000
    networks:
      - chart-tool-network
  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
      - --logpath=/dev/null
    volumes:
      - data:/data/db
    networks:
      - chart-tool-network
  browserless:
    image: browserless/chrome:latest
    networks:
      - chart-tool-network
    restart: always
networks:
  chart-tool-network:
volumes:
  data:
