version: '3'
services:
  app:
    volumes:
      - ./:/chart-tool
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    ports:
      - '3000:3000'
      - '8080:8080'
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongo:27017/meteor
      PORT: 3000

  mongo:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db

volumes:
  data:

meteor mongo --url
